version: 2.1

aliases:
  node-executor: &node-executor
    docker:
      - image: circleci/node:10

  e2e-executor: &e2e-executor
    docker:
      - image: cypress/browsers:chrome69

  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cypress-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cypress-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: packages

  e2e-test-workflow: &e2e-test-workflow
    filters:
      branches:
        ignore:
          - master
    requires:
      - bootstrap

  test_template: &test_template
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - <<: *attach_to_bootstrap
      - run: yarn test:unit

commands:
  e2e-test:
    parameters:
      trigger_pattern:
        type: string
        default: "packages/*|.circleci/*"
      test_path:
        type: string
      test_command:
        type: string
        default: "" # if unset, e2e-test.sh specifies the command
    steps:
      - checkout
      - run: ./scripts/assert-changed-files.sh "<< parameters.trigger_pattern >>|<< parameters.test_path >>/*"
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - <<: *attach_to_bootstrap
      - run: ./scripts/e2e-test.sh "<< parameters.test_path >>" "<< parameters.test_command >>"

jobs:
  bootstrap:
    <<: *node-executor
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - persist_to_workspace:
          root: packages
          paths:
            - "*"

  lint:
    <<: *node-executor
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: yarn lint:ci

  unit_tests:
    <<: *node-executor
    <<: *test_template

  e2e_tests_auth:
    <<: *e2e-executor
    steps:
      - e2e-test:
          test_path: e2e-tests/auth
          trigger_pattern: "packages/amplify-material-ui|.circleci/*"

workflows:
  version: 2
  build-test:
    jobs:
      - bootstrap
      - lint
      - unit_tests:
          requires:
            - bootstrap
      - e2e_tests_auth:
          <<: *e2e-test-workflow
